### ISSUE TITLE
Without making change to our CI, all environments created from cache now failing for any commit

### ISSUE THREAD

**Issue by obrienpja** [actions/cache#1031]

**Comment by obrienpja** [comment]
We are having an issue, possibly with caching on our repo https://github.com/Qiskit/qiskit-metal. Our CI suddenly broke because one of our dependencies, PySide2, is not in our environment. Based on this issue, we are writing to you, but I have closed the issue for now, because we are going to consult with the GitHub Actions Customer Support first.

**Comment by obrienpja** [comment]
@priti-ashvin-shah-ibm

**Comment by obrienpja** [comment]
We deleted all old caches and had GitHub create a new cache entry. Unfortunately, the same issue persists. We also tried creating our environment locally identically to how it is being created by GitHub Actions, and the environment was created without issue and was able to import PySide2.

**Comment by pdotl** [comment]
Hi @obrienpja, I checked your previous successful runs and recent failed runs and found you are running `apt install` which has probably broken with the latest ubuntu release. This has happened because now the github hosted runner image `ubuntu-latest` points to `ubuntu-22.04` instead of the previous `ubuntu-20.04`. For now, try running your workflows with the pinned ubuntu version i.e `ubuntu-20.04` in `runs-on` or use a self-hosted image that runs ubuntu 20.04. Closing this issue as it is not related to `actions/cache`.

**Comment by priti-ashvin-shah-ibm** [comment]
https://github.com/actions/setup-python/issues/570

@pdotl , thank you for responding.  Unfortunately, [our implementation](https://github.com/Qiskit/qiskit-metal/pull/887) of your suggestion did not resolve our issue.  We wrote a different issue in the setup-pyhton repo.  If you would suggest any other resolution, we would welcome insight into this problem of CI unexpectedly stop working.  We still feel there is something with the environment, and need to have CI working again.
