### ISSUE TITLE
Post cache takes 30 seconds even if cache was hit

### ISSUE THREAD

**Issue by petkaantonov** [actions/cache#1032]
<img width="1387" alt="kuva" src="https://user-images.githubusercontent.com/829734/208480504-96bdd11e-2fd3-42db-bc72-209e36be60f2.png">

This takes a substantial chunk of our build times. It should not even take a millisecond because the cache was hit there is no need to do anything.

**Comment by kotewar** [comment]
Hi @petkaantonov,

This occurs because the post step is _expected_ to take time in seconds as it resolves inputs and paths and we can’t do much about it.

To take care of such customer asks, we released two new actions `actions/cache/restore` and `actions/cache/save` in beta mode for customers to test. The `save` action can be used with `if` [condition](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) to check if the `cache-hit` is not equal to `true` hence skipping the step entirely without evaluating anything.

Please do try this out and let us know if it solves your problem.

Links for your reference-
- [Discussion with use cases](https://github.com/actions/cache/discussions/1020)
- [Beta release](https://github.com/actions/cache/releases/tag/v3.2.0-beta.1)
- [Usage and Feedback](https://github.com/actions/cache/discussions/1028)

**Comment by petkaantonov** [comment]
Thanks, those will work
