### ISSUE TITLE
Windows does not find old cache

### ISSUE THREAD

**Issue by jpfeuffer** [actions/cache#1067]
```
Run actions/cache@v3
  
Cache not found for input keys: Windows-ccache-feature-actions_ccache-1655, Windows-ccache-refs/heads/feature/actions_ccache, Windows-ccache-feature-actions_ccache, Windows-ccache-develop, Windows-ccache-
```

But it is DEFINITELY here! And from the same branch!
https://github.com/OpenMS/OpenMS/actions/caches#:~:text=Windows%2Dccache%2Drefs/heads/feature/actions_ccache%2D1648

Check yourself
https://github.com/OpenMS/OpenMS/actions/runs/3885525892/jobs/6629509336

**Comment by vsvipul** [comment]
@jpfeuffer Can you please try this after one more time after[ this ](https://github.com/OpenMS/OpenMS/actions/runs/3885525892/jobs/6629509336)run saves cache and add the results here ?  (This might be due to different version being created for a newer cache version released 2 days back. P.S. We use combination of version and key to decide if restore should happen. You can check the version using the list caches API https://github.com/actions/cache#cache-version )

**Comment by jpfeuffer** [comment]
I see. I will report back. Can I somehow fix the version, such that this will not happen again?

**Comment by vsvipul** [comment]
Here, I meant neither but the version of cache, which i have linked.  
We recently introduced a new input called enableCrossOsArchive will invalidated your old cache and created a new version number if this is set to false(default) in the latest cache version v3. This is happening [here.](https://github.com/actions/toolkit/blob/06c3c38ef2b06460057795826f7977cec630099f/packages/cache/src/internal/cacheHttpClient.ts#L88)
This is just because the logic to calculate version changed on our end. You don't need to do anything and from next time onwards there shouldn't be any issue in restoring cache. I'm closing this issue. Feel free reopen if you still face any more problem.
