### ISSUE TITLE
Post action cache issue

### ISSUE THREAD

**Issue by Labbs** [actions/cache#118]
Hello,

If the post cache step has an error, the step is not in error.
In this case, the pipeline continue.

![Screenshot 2019-11-27 at 15 25 25](https://user-images.githubusercontent.com/1633745/69731423-2d07b580-112a-11ea-9a6d-9191b851a13a.png)

**Comment by dhadka** [comment]
Hi @Labbs.  Yes, this is by design.  The caching action suppresses most, if not all, errors.  The reasoning is that we do not want a caching failure to cause the entire pipeline to fail.  This is especially true with transient issues, such as a network or server outage.

Please also note that the caching action currently only works with directories, which is why the step is failing.  We plan to fix this in the next major release.

**Comment by Labbs** [comment]
@dhadka Thanks for the response.
I understand the point. Normally the following job must fail because the cache does not exist.
This will only be a problem for people who use a cache that is not linked to a file (yarn.lock for example). It could end up with an outdated cache, and potentially have problems.

**Comment by dmitry** [comment]
Might be an issue that `/tmp` path is emptied after running all the steps?
