### ISSUE TITLE
Caching fails with illegal character plus `+`

### ISSUE THREAD

**Issue by eyal0** [actions/cache#119]
Simliar to #53 but #53 is closed and this issue still exists.

**Comment by dhadka** [comment]
Yes, thanks for creating an issue for this.   #53 was closed because the issue with `/` was fixed, but there are still a few known invalid characters (`+` and `\`).  We are working on a fix, but given that we will need to change the API, this fix will be included in v2 of the action (along with a bunch of other improvements).

For anyone who may encounter this issue, the workaround is to sanitize the key by removing these characters.  See https://github.com/actions/cache/issues/53#issuecomment-552052769 for details.

**Comment by joshmgross** [comment]
This is now fixed in the latest release, see [this run](https://github.com/joshmgross/cache-canary/commit/fd0a71621a84303ae2ac9f0d77e2e0db2cd254ae/checks?check_suite_id=387018978) where the key contains `+`

Fixed in #128 with the new APIs to put the key in the `POST` body

**Comment by eyal0** [comment]
Thanks for this.  I also see that, in addition to `[command]`, '[debug]' is also a special prefix in github actions.  Good to know.

**Comment by joshmgross** [comment]
@eyal0, yep. There are a few of them used to control syntax highlighting. Most come from [Logging Commands](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands), but you can use the prefixes in any string output if you just want the highlighting.

Off the top of my head, there's `[warning]`, `[error]`, `[debug]`, `[command]`, and `[debug]`.

Check out https://github.com/actions/toolkit if you want to use these commands from node-based actions
