### ISSUE TITLE
Cache consistently misses despite same key, branch, and operating system

### ISSUE THREAD

**Issue by Sainan** [actions/cache#1229]
I'm aware of the [cache scopes](https://github.com/actions/cache#cache-scopes), yet this simple workflow:
![image](https://github.com/actions/cache/assets/63328889/88d59485-c706-4783-a61a-f4f5aa075658)
Causes the cache to consistently miss & create a new cache for each run:
![image](https://github.com/actions/cache/assets/63328889/628f1e3b-c5fa-467f-a798-836851a10928)
This _might_ be because `env.EMSDK` is some funny volatile value like `/home/runner/work/_temp/ea04f67e-177b-46bb-a310-10d3ea9f9115/emsdk-main`.

**Comment by vinmassaro** [comment]
Running into the same issue - working on the default branch, cache is created in one job and attempting to restore in another. Every time, it outputs "Cache not found for input keys" and lists out the attempts, each of which matches the created key.

**Comment by Sainan** [comment]
Ah yeah I didn't say but "senpai" is my default branch, because "master" was apparently not woke enough.

**Comment by allwalte** [comment]
According to the [docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key), the scope is branch, key, and version, and version "is a way to stamp a cache with metadata of the path and the compression tool used while creating the cache".  So if the path is different, then the cache will not hit because the version is different, even if the other two criteria (branch and key) are the same.  Given that you do have that "volatile" value as part of your path I'm guessing this is probably what's happening?

If you use the cli command ```gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"   /repos/<OWNER>/<REPO>/actions/caches``` , you can see info about the caches.  In my similar case, I could see two that had the same ref and key, but the version is different (and that's not exposed in the UI when viewing).

**Comment by Sainan** [comment]
That makes some sense, but is extremely weird behaviour because the path being randomised is literally what happens for each new job run on an actions worker?

The path should be normalised before being used for the algorithm that calculates the _version_.

Also, no way to overwrite the version myself... so, this workflow step is effectively useless.

**Comment by allwalte** [comment]
I admit this is the first time I've dug into cache behaviour, but...looking, I can see most of our jobs are hitting the cache fine except for the one where we're actually deliberately changing the path after the portion that github creates, which is where it hits the "dup".  So it does seem to be working as expected for us.  The one difference in what we've got from what you've shown though is that in the path we're using ```${{ github.workspace }}/<our path>``` where you're using ```env.EMSDK```, so maybe gh does some magic where it ignores the part of the path that changes as part of the ```${{ github.workspace }}``` var specifically?

**Comment by benebene84** [comment]
I have a similar issue where I restore a cache - a build artifact from another step - in one workflow step, which works just fine. 
I need that artifact restored as well in an another workflow step, but this step runs in a docker image, so I can't restore it because keys don't match. 

So I assume this is also due to the version. Quite annoying. Would be great to have a possibility to overwrite or disable it.
