### ISSUE TITLE
Can it be used without involving node.js?

### ISSUE THREAD

**Issue by KOLANICH** [actions/cache#137]

**Comment by joshmgross** [comment]
Hey @KOLANICH,

Currently no, this action is written in TypeScript and requires node.js. Right now there are only two ways to write actions, node.js and container actions, and we chose node due to better cross platform support.

That being said, it *could* be possible to cache without using this action and without using node, it's just not currently.

What's your use case that prevents using node? What language/ecosystem would be preferred?

**Comment by KOLANICH** [comment]
I prefer not to use node. npm is plagued with malware, and node ecosystem is centered around npm. I don't know why pypi is not plagued so much. Maybe it is just underresearched.

>Currently no, this action is written in TypeScript and requires node.js. 

Are there any docs on the API used? What should I do to rewrite the action to python or bash? I mean I guess it does something better than `git clone --depth=1 https://github.com/$GITHUB_REPOSITORY`. Could you, please, give me a high level description of what it does? Thank you.

>What language/ecosystem would be preferred?

If it is possible, I prefer a single `git ` command, or maybe a couple of them. But if complex scripts with variable passings are needed, python3 is much more suitable for scripting than bash.

**Comment by joshmgross** [comment]
>Are there any docs on the API used?

The API is internal so it's not fully documented. See https://github.com/actions/cache/issues/22#issuecomment-548539076

>What should I do to rewrite the action to python or bash?

The cache is effectively a single-file store addressed by a cache `key` and a `scope` that references a specific branch of the repository.

You'd want some sort of REST client (`curl` if you're writing a bash script). See https://github.com/actions/cache/blob/master/src/cacheHttpClient.ts for what this node action is doing.

**Comment by KOLANICH** [comment]
Nice, thank you. 

I want to keep some data in a db. For example I may want to keep track how many invalid issues (issues not following the template or the issues when a user haven't replaced the template with own data) a user creates and if a user creates more than `threshold` invalid issues ban him automatically. I guess I would have to save the db and cache and then load it. It is inefficient.

But is it efficient to use the cache as a key-value store for small records? Are there any guarantees that the cache won't be erased?

Or should I ask GH bring up a postgres or mongo for this purpose?

Or should I just encode the info into yaml/json and store it in a special locked issue?

**Comment by joshmgross** [comment]
>But is it efficient to use the cache as a key-value store for small records? Are there any guarantees that the cache won't be erased?

No, I'd say it's not very efficient. Since the cache is meant as a "best-effort" improvement for build times, there's no guarantees that the cache will exist and can be evicted for multiple reasons. On top of that, caches are immutable, so each time you save data, you create a new cache and a new key.

For your use case, you need a persistent data store (either a Database or a file stored with your action).

You could use [`services`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idservices) to spin up a database container.

>Or should I just encode the info into yaml/json and store it in a special locked issue?

That's also an option, though it may be easier to store that yaml/json in a file in your repo instead of an issue.

The action could:
1. Trigger off of an issue creation
1. Lint the issue
1. If lint fails, load your json file, modify it, and commit it back to the repo

Commits triggered using the GitHub token in Actions will not trigger more workflows (which is ideal in this case). You may need a separate PAT with the permissions to block users.

**Comment by KOLANICH** [comment]
Thanks for the info.
