### ISSUE TITLE
Cache-Hit set to string, not boolean, as of v4.1.0

### ISSUE THREAD

**Issue by bigdogwillfeed** [actions/cache#1466]
After a recent upgrade, our runners started behaving differently on cache miss.

As of 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9, a step defined with `if: steps.cache-release.outputs.cache-hit` would be skipped if the "cache release" job missed the cache, as intended. As of 2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2, the job now runs on cache miss, despite clearly missing the cache.

Here's a relevant snippet of the run with debug logging enabled
```
Cache not found for input keys: release-0e0ceb0ce2360a93ec77b898ac06177b7429666b
##[debug]Node Action run completed with exit code 0
##[debug]Save intra-action state CACHE_KEY = release-0e0ceb0ce2360a93ec77b898ac06177b7429666b
##[debug]Set output cache-hit = false
##[debug]Finishing: Cache release folder
<snip>
##[debug]Evaluating condition for step: 'Panic if build already exists'
##[debug]Evaluating: (success() && steps.cache-release.outputs.cache-hit)
##[debug]Evaluating And:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'cache-release'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'cache-hit'
##[debug]..=> 'false'
##[debug]=> 'false'
##[debug]Expanded: (true && 'false')
##[debug]Result: 'false'
##[debug]Starting: Panic if build already exists
```

**Comment by madebr** [comment]
I'm seeing the same bad behavior.
As a workaround, I currently added a string comparison to my workflows:
```
      if: ${{ (!steps.cache-restore.outputs.cache-hit || steps.cache-restore.outputs.cache-hit == 'false') }}
```

**Comment by Jason3S** [comment]
This is cause by #1404, which was a major breaking change.
It is not clear why the change was necessary.

**Comment by joshmgross** [comment]
This should be fixed in https://github.com/actions/cache/releases/tag/v4.1.1, the `v4` tag will be updated soon.

**Comment by Jason3S** [comment]
@joshmgross, 
Thank you.

**Comment by joshmgross** [comment]
@itchyny I agree that using `cache-hit` as-is is confusing and difficult.

Our priority is to maintain the existing behavior and avoid unnecessary customer friction.

The existing `cache-hit` output really has two purposes:
1. Indicates if a cache was restored (`''` vs non-empty string)
2. Indicates if an exact cache match was found (`'true'` or `'false'`)

In the future, I'd like to break that up into two outputs so that we don't need this odd ternary string to represent all 3 cases. Ideally that would come with proper support in the Actions runner for typed outputs, but that's not currently on our roadmap.

Alternatively, we adopt the changes that were reverted and properly release that as a breaking change with a `v5` of this action. Major versions are not something we do often - we end up with mixed adoption across major versions and either have to maintain multiple major versions or leave users on older major versions out of important security updates or bug fixes.

I'm going to call this closed for now, but I'm open to further feedback on how we can improve `cache-hit`. Feel free to open an issue or discussion if you'd like to discuss that further.
