### ISSUE TITLE
cache post-setup failures

### ISSUE THREAD

**Issue by kapilt** [actions/cache#282]
all of a sudden this morning our cache post-setup started failing with 

```
Post Set up cache 15s
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/2c4ed222-ac5c-466d-b163-19853e6fd4a2/cache.tgz -C /home/runner/work/cloud-custodian/cloud-custodian/.tox/py37 .
[warning]Cache service responded with 500 during chunk upload.
events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
```

**Comment by LJunghansCode** [comment]
Same error here this morning!

**Comment by dhadka** [comment]
Thanks for reporting!  Issue was caused by an automated OS update that started failing requests with large bodies.  We have been deploying a fix using the old OS image.  The fix has already deployed to 2 of the 3 scale units, so this may be mitigated for some of you.  Will be fixed on the last scale unit in about 20 minutes.

**Comment by LJunghansCode** [comment]
Thanks a ton! Just re ran and all is well. <3

**Comment by dhadka** [comment]
Should be mitigated everywhere, now.  Sorry for the inconvenience.

**Comment by kapilt** [comment]
thanks, lgtm

**Comment by mikkame** [comment]
I get same error today
