### ISSUE TITLE
Documentation on multiple caches in a single script

### ISSUE THREAD

**Issue by binkley** [actions/cache#288]
The caching action is amazing -- thank you!

*A documentation question/request*

I'd like to use 2+ caches in my script.  The top-level documentation (`README.md`) for this repo does not provide an example.  I'll learn how to do this via trial-and-error, and would like an example in the documentation.

*Use case 1*

My JVM-based project provides both Maven and Gradle build scripts.  The user decides which they prefer.  I'd like caching for both `~/.m2` and `~/.gradle`.

*Use case 2*

I have a local build script for my project, and I provide a https://github.com/batect/batect script for use in CI/CD pipelines (or when a dev wants to locally investigate CI/CD failures).  I'd like caching for both the local build system, and for `~/.batect'.

**Comment by aviflax** [comment]
I have a similar situation; [my project](https://github.com/FundingCircle/md2c8e) uses [Clojure](https://clojure.org/) with the [`tools.deps`](https://github.com/clojure/tools.deps.alpha/) toolkit for dependency management. That toolkit is able to retrieve artifacts from [Maven](https://maven.apache.org/) repositories and it’s also able to retrieve libraries as source from remote [Git](https://git-scm.com/) repositories, e.g. those hosted on GitHub. It stores the former in `~/.m2` and the latter in `~/.gitlibs`.

My project specifies both types of dependencies, so I’d like to be able to cache both of those directories.

It’d be ideal if I could do so by specifying `paths` instead of `path`, and just supply both paths to the one action invocation/instance. (This is how my [CircleCI](https://circleci.com/) jobs work.) But if I have to invoke/instantiate/specify the cache action twice, I can live with that — but I have no idea whether it’ll work. I’ll try it out, but my point is: I agree it’d be great if the docs would address this sort of scenario.

**Comment by dhadka** [comment]
For now, you'll need to create two separate cache steps with two different keys and paths.  An example of using multiple cache steps is here: https://github.com/actions/cache/blob/master/examples.md#haskell---cabal.

Support for multiple paths in a single cache was added in PR https://github.com/actions/cache/pull/212 and will be included in @v2 of this action.  However, it hasn't been published yet as we are still working on a few other features.

**Comment by aviflax** [comment]
Great, thanks @dhadka!

**Comment by ahdbilal** [comment]
Closing this issue as v2 has been released
