### ISSUE TITLE
cache misses on cache key saved by previous PR

### ISSUE THREAD

**Issue by toffaletti** [actions/cache#310]
See analysis in this thread, copied below.

https://github.com/apple/swift-protobuf/pull/973#discussion_r425181691

--------------

I agree it seems like the cache should have had a cache hit, in 
https://github.com/apple/swift-protobuf/runs/664761605?check_suite_focus=true I see
> Cache not found for input keys: Linux-ubuntu-18.04-protobuf-cf601047ebf87cf7f443753ded41132eb689cb10.

then later in Post Cache:

> Cache saved successfully

And in the other parallel builds:

> Running JavaScript Action with default external tool: node12
> [warning]Cache already exists. Scope: refs/pull/991/merge, Key: Linux-ubuntu-18.04-protobuf-cf601047ebf87cf7f443753ded41132eb689cb10, Version: (null)

But then 3 days later in your PR a cache miss for the same key:

https://github.com/apple/swift-protobuf/runs/674773193?check_suite_focus=true

> Cache not found for input keys: Linux-ubuntu-18.04-protobuf-cf601047ebf87cf7f443753ded41132eb689cb10.

However, I do see at least one cache hit:

https://github.com/apple/swift-protobuf/runs/675011233?check_suite_focus=true

> Cache Size: ~182 MB (190677067 B)
> /bin/tar -xz -f /__w/_temp/90437206-2a9e-46a5-9320-7515799d57c5/cache.tgz -C /__w/swift-protobuf/swift-protobuf/protobuf
> Cache restored from key: Linux-ubuntu-18.04-protobuf-6935eae45c99926a000ecbef0be20dfd3d159e71

It seems like the cache isn't reliable.

**Comment by dhadka** [comment]
Hi @toffaletti, I took a look and it seems to be working as designed.  The behavior you're seeing is the result of the **cache scope**.  There are some details in the docs under [Restrictions for accessing a cache](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), but I'll also try to explain how it's working in your particular examples below.

Essentially, we decided for security reasons we did not want to allow, for example, the master branch to access a cache created in a PR.  A malicious user could potentially create a PR that injected a vulnerability into the cache, which if you then used that cache to build production binaries from master, would lead to a security issue.  Hence, there are restrictions on when you can read from and write to a cache.

So for the case of https://github.com/apple/swift-protobuf/runs/664761605?check_suite_focus=true and https://github.com/apple/swift-protobuf/runs/674773193?check_suite_focus=true, they are from two different branches/PRs, which are not allowed to share a cache.

Where caching has the most benefit is when the PR is merged into master.  At that point, the cache is created in the master scope, which all PRs can read from.

The second example, with https://github.com/apple/swift-protobuf/runs/675011233?check_suite_focus=true, does have a cache hit because the cache was created previously by https://github.com/apple/swift-protobuf/runs/674852172?check_suite_focus=true#step:20:5 when that PR was merged into master.

I hope that helps explain why you're seeing this behavior.  It makes using the cache less efficient, since the cache can't be shared all the time, but we hope the security benefit outweighs the efficiency loss.

Best regards!

**Comment by toffaletti** [comment]
That makes sense and I now remember reading this in documentation, but it was a while ago and when I went back and skimmed it today the only thing I was focused on was the size limits and 7 day expiration period.
