### ISSUE TITLE
Cache not found for input keys

### ISSUE THREAD

**Issue by FDiskas** [actions/cache#385]
For some reason. I tried both v1 and v2 - same results
![image](https://user-images.githubusercontent.com/468006/88637045-55cdb980-d0c2-11ea-8920-03c467be3509.png)

**Comment by dopplershift** [comment]
I'm seeing this quite a bit as well.

**Comment by dhadka** [comment]
@FDiskas @dopplershift This is usually a symptom of an error occurring while creating the cache.  Most of the time this is caused by insufficient file permissions, but would need to look at each case individually to see what the root cause is.  I would recommend the following:

1. Edit the workflow file and change the cache key.  For example, add a `-v2-` in the string.  This will force it to create a new cache.
2. Watch the Post Cache step output.  **The Post Cache step will be successful even if an error occurs, so please expand the logs to see the output.**
3. Address the error (or post the logs here if unable to fix it)

**Comment by agilgur5** [comment]
Sounds like a duplicate of #144
