### ISSUE TITLE
Cache seems to be OS version specific (at least on Windows)

### ISSUE THREAD

**Issue by Vampire** [actions/cache#387]
I use this cache action to transport files between jobs.

I know it is also possible with artifacts, but imho they are not really suited for the task, as artifacts are things that should persist after the workflow finished and also there is no way to delete to date, so using artifacts is exposing internal workflow state which seems wrong to me.

Instead I use this cache action with `${{ github.run_id }}` as cache key as this is an id uniqe to the workflow run, so the cache is used exactly within the workflow and that's it.

I was pretty successful with this tactic so far, as I build a WSL based action and thus all happens only on the `windows-latest` environment where WSL is available.
I have a build job that builds the action and then several test jobs that test the action, using the built files from the build job.

Now comes the quirk. I added a runtime check that WSL is available in case someone uses my action on `windows-2016` environment and also made a test job for this.

Executing the action also fails, but for the wrong reason. It fails for not finding the `action.yml` file because the cache action had no hit.

If I add a second build action that builds on 2016 and fills a second cache bucket, then use that cache bucket on the windows 2016 test, it works.

Now the question is, why do I not have a cache hit when filling the cache on `windows-2019` and restoring it on `windows-2016` while the cache key is correct.

You can see the differences in these two runs, but don't get confused from all being green.
There is a `continue-on-error: true` as the action is expected to fail, it just fails for the wrong reason in one of the runs.

Bad run: https://github.com/Vampire/setup-wsl/runs/936481421?check_suite_focus=true
Here the `Build` job fills the cache with key `191698355` that is then used in all `Test` jobs.
In all except for the `Test 'windows-2016' environment` job this works fine.
In the `Test 'windows-2016' environment` job though, there is a cache miss for key `191698355`,
the `Execute action` step fails wrongly with `Can't find 'action.yml'` and the post-part stores an empty cache entry.

Good run: https://github.com/Vampire/setup-wsl/runs/936483860?check_suite_focus=true
Here I added a second build job `Build on windows-2016` that does exactly the same things as `Build`, just on `windows-2016` and is then used by the `Test 'windows-2016' environment` job which properly fails with `This Windows environment does not have WSL enabled` as expected.

So it seems the build cache is somehow environment-specifc down to the version of the OS.
If this is really the case, this is pretty bad, there are many OS-independent things like JavaScript or Java files.
There is no reason to not reuse them between different platforms, let alone different versions.

**Comment by dhadka** [comment]
@Vampire Yes, this is a known issue.  It's detailed in [this issue](https://github.com/actions/cache/issues/301), but the summary is BSD `tar` with `zstd` compression hangs on large files.  If you look at the debugging output in your logs, you'll see we print `tar --version` and the two Windows versions display different tar versions (GNU and BSD tar). Because BSD tar hangs, we disable `zstd` compression and fall back to `gzip` when we detect BSD tar.  However, this means the caches can't be interchanged.

I think we can replace `tar --use-compression-program zstd` with `tar ... | zstd ...` and not sacrifice too much performance, but currently we have been focusing on other priorities and likely won't be able to have a fix for a few weeks.  This is open source, however, so we do welcome contributions 😄. The relevant code is over in the [actions/toolkit](https://github.com/actions/toolkit/blob/e3c6237940b32283ebcb73524f0155fa273ba942/packages/cache/src/internal/cacheUtils.ts#L86) repo.

**Comment by Vampire** [comment]
I see, as actions/cache#301 is still open for a fix, I'll close this one and watch over there, thanks.
