### ISSUE TITLE
Decompression of cache is slow - 850MB take 49s

### ISSUE THREAD

**Issue by shugybugy-assaf** [actions/cache#435]
@dhadka 
#267 is a gr8 improvement, but still not as fast as one would expect.
Download is fast now, however untarring the cache is still VERY slow.
It takes us whole 49s to untar only 850MB. (we cache python installation)
On my VM it takes only 15seconds using gzip which should be slower than zstd.

Is it possible that compression is mal-configured to a strict compression-level ? Is the disk super-duper slow on writing many files ? 

Here is the log that show the decompression step takes 49s.
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/47495734/96222932-ca174b00-0f95-11eb-8b3d-41a28f9e301d.png">

The  decompression command that takes 49s is (copied from the logs above)
`/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/6b8290d8-2585-4bf3-be99-27773859afcd/cache.tzst -P -C /home/runner/work/datascience/datascience`

We use the approach explained below to cache the python installation directory
https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d

_Originally posted by @shugybugy-assaf in https://github.com/actions/cache/issues/267#issuecomment-709860880_

**Comment by dhadka** [comment]
Hi @shugybugy-assaf, thanks for the inquiry.

We don't set the compression level for `zstd`, so it will just use the default of `3`.  

I suspect the performance difference is likely with the specs of the runner compared to your VM.  Linux runners use the `Standard_DS2_v2` VM ([specs](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series)) which gives it 2 vCPUs, 7 GBs of RAM, and a max uncached disk performance of 6400 IOPS / 96 MBps throughput.  If it is writing a bunch of small files, I could see the disk perf being a bottleneck.

**Comment by shugybugy-assaf** [comment]
@dhadka Thank you for the answer - that is interesting !

So, to make sure I understand correctly - we suspect that it's hardware diff.
Therefore, if I edit the workflow such that it zips the cached directories and then unzips then into a temporary dir -
the explanation above predicts that performance of unziping shall be similar.

Is that I right ?

**Comment by dhadka** [comment]
I would assume so.  If you'd like to test that hypothesis, the cache action should print out the command it's using to create and extract the archive, which would give the baseline for expected performance.  If you find some combination of options that provides better performance, we would definitely be interested. There's some discussion in https://github.com/actions/cache/pull/270 about the specific options used for `zstd`.

**Comment by stefanbuck** [comment]
In my case, it takes 23 seconds to decompress 270MB on a linux box. The cache contains a node_module folder meaning a lot of small files are involved. For a single workflow, this isn't a huge deal, but we run 12 workflows and each of them is using the cache step meaning we spent 276 seconds (4.6 minutes) restoring cache files. 

This must be a common problem for projects using npm/yarn which consists by nature of many small files. Yarn 2 tries to solve this issue with a feature called  [Plug'n'Play](https://yarnpkg.com/features/pnp). A `.pnp.js` file is generated instead of Node modules.  

Anyway, not everyone is using yarn neither yarn 2 or Plug'n'Play. I think there is a huge opportunity to save a tone of time, money, and resources by investigating how to improve caching for such package managers. 

From browsing through the `node_module` folder I can see many files that might not be required from the package at run time.

|File extensions|Total|
|---|---|
|Markdown files|2763|
|Test files| 394|
|.editorconfig|45|
|.travis.yml|167|
|.eslintrc|80|

... and much more


Worth mentioning, that npm allows developers to exclude files using the [.npmignore](https://docs.npmjs.com/cli/v6/using-npm/developers) file. It works similar to a `.gitingore` file. They also provide a `files` property for the `package.json` file which works the opposite. However, this seems to be rarely leveraged to keep the package small. Maybe this is just an educational issue. 

![image](https://user-images.githubusercontent.com/1393946/101877029-acc5be00-3b8d-11eb-90ce-4416b023fd80.png)
