### ISSUE TITLE
Save a large cache failed (3Gb+)

### ISSUE THREAD

**Issue by retyui** [actions/cache#455]
I tried to cache an iOS Pods build (via [Improve iOS CI build times with CocoaPods caching](https://blog.takescoop.com/improve-ios-ci-build-time-with-cocoapods-caching-4a049ee45e63)), Folder size that I tried to cache about 3.4Gb

But after the 40s postscript of cache action failed with the next output:
```
2020-11-10T09:01:02.5590970Z Post job cleanup.
2020-11-10T09:01:28.5154380Z [warning]reserveCache failed: connect ETIMEDOUT 13.107.42.16:443
```

---
https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 5 GB. If you exceed this limit, GitHub will save your cache but will begin evicting caches until the total size is less than 5 GB.

**Comment by dhadka** [comment]
Hi @retyui, is this using a self-hosted runner?  Some users have observed timeouts due to slower upload speeds.  One workaround is to use smaller chunk sizes during upload (the default size is 32 MBs).  This can be configured as shown here - https://github.com/actions/cache/issues/415#issuecomment-707196575

**Comment by retyui** [comment]
@dhadka 
I use free public runner's, I restarted a workflow and seems this problem gone
