### ISSUE TITLE
Skip post cache

### ISSUE THREAD

**Issue by nroose** [actions/cache#457]
We have several jobs that we run at once, and they use the same cached files, and if they update them, they would make the same updates. We don't need to update the cache for all of them, just for one. And actually some of them usually fail because they are all trying to update the cache at the same time. So we would like to skip the cache for all the other jobs.

We may also only want to update the cache for specific branch patterns to save time on branches that won't likely be in a state that gets a valid cache hit anyway, so they shouldn't save the cached files.

Other than that, it works great!

Thanks!

**Comment by rcowsill** [comment]
Would be good to have this as well as the option to force a cache update (#342)

**Comment by eyal0** [comment]
Here's my solution: https://github.com/actions/cache/pull/498#issuecomment-753804797

**Comment by haggholm** [comment]
Another use case: I have a number of jobs sharing a cache (`node_modules` etc.). In one of them, I want to trim these files (to build smaller Docker images), but if I delete parts of the cached files, they will be uploaded, which means the cache is wrong for all other jobs.

I want to treat the cache as pull-only and discard local changes—rather like the `"pull"` behaviour you can do with Gitlab CI.

**Comment by aparna-ravindra** [comment]
> I want to treat the cache as pull-only and discard local changes

If there is a cache hit on the primary key, the post action does not save the cache. Therefore, even if you make local changes, it should not affect the already cached content. Effectively, the local changes are discarded once the job finishes.

**Comment by aparna-ravindra** [comment]
> And actually some of them usually fail because they are all trying to update the cache at the same time

This is expected because of the jobs running in parallel. However, only one job will succeed in creating the cache while others will simply exit.

**Comment by eyal0** [comment]
> > I want to treat the cache as pull-only and discard local changes
> 
> If there is a cache hit on the primary key, the post action does not save the cache. Therefore, even if you make local changes, it should not affect the already cached content. Effectively, the local changes are discarded once the job finishes.

It's a shame.  The easiest paradigm would be to allow users to treat the cache like a regular file system.  The users just specify the filename and if they want to read it, write it, overwrite it, etc.  And that's it.

Currently it's readable and you can write it but you can only write it if it doesn't already exist.  No overwrite is allowed.

I know that this would take a change not just in the action but also in the server because it's actually the *server* that is not allowing overwrite.

**Comment by aparna-ravindra** [comment]
> Currently it's readable and you can write it but you can only write it if it doesn't already exist. No overwrite is allowed.

This is correct. This open issue in the [roadmap](https://github.com/github/roadmap/issues/471) will allow cache deletion. So, you will be able to delete+create new to update an existing cache.

**Comment by simonrussell** [comment]
We're looking for this functionality -- we have a large cache which we only want to update on the main branch.  If a whole bunch of branches update it, we'll quickly start evicting useful caches due to the 10Gb limit.

It's unlikely it'll be an exact match on the branch (think Dependabot package updates) so the current design will always create a new cache, which we don't want.  But we do want the benefit of the cache being a 95% match to what we need.

**Comment by kotewar** [comment]
@simonrussell so if I understood it correct, you are looking only for ability to restore the cache and do nothing else with this action.

Is my understanding correct?

**Comment by simonrussell** [comment]
@kotewar pretty much -- depending on what branch we're on, so some runtime level of control over whether it goes and updates the cache would be good.

**Comment by kotewar** [comment]
Hey all, 👋🏽 

We have created a [discussion](https://github.com/actions/cache/discussions/1020) with a proposal that we feel will solve this problem, do let us know your feedback, thanks 😊

**Comment by kotewar** [comment]
We have released a new [restore](https://github.com/actions/cache/tree/main/save) action that solves this issue, hence closing it.
