### ISSUE TITLE
Despite writing to cache, cache cannot be hit

### ISSUE THREAD

**Issue by aaronsky** [actions/cache#484]
Hey folks. I believe this pertains to this repo, but feel free to redirect me if I'm off-base. 

I've got a workflow that is scheduled to run once a day and take advantage of a cache between each day. Since it's intended to always write the result of this, I've configured my workflow to fetch yesterday's cache if available, fetch today's cache (but expect not to hit), run the program to write the new cache file, and then write to today's and yesterday's cache in reverse order. You can see this in more detail [in my workflow file here](https://github.com/aaronsky/newcity/blob/main/.github/workflows/daily.yml#L19-L37). 

I am able to observe the cache written over consecutive days during the post-run action. However, the subsequent day's job is never able to hit cache. 

1. [First day, attempts to hit cache newcity-50-1 and newcity-50-2, fails, and writes the paths to cache](https://github.com/aaronsky/newcity/runs/1518885541?check_suite_focus=true)
1. [Next day, attempts to hit cache newcity-50-2 and newcity-50-3, fails, and writes the paths to cache](https://github.com/aaronsky/newcity/runs/1525537620?check_suite_focus=true)
1. [Following day, attempts to hit cache newcity-50-3 and newcity-50-4, fails, and writes the paths to cache](https://github.com/aaronsky/newcity/runs/1532236131?check_suite_focus=true)
1. And so on

Am I misunderstanding something vital about how the cache is supposed to work? Is there anything I can do to debug this further?

**Comment by rcowsill** [comment]
The cached paths need to match, not just the key. The "today" step of the first run stored newcity-today.json with the key `flavors-50-2`. The "yesterday" step of the next run tries to restore `flavors-50-2`, but it's looking for newcity-yesterday.json which doesn't exist under that key.

Instead of running multiple cache actions you can use the `restore-keys` feature. That lets you specify partial matches to check if the main key isn't found. For example, adding a restore-keys list containing `flavors-` would find the newest cache with a key starting with `flavors-`. The paths still need to match as above.

There's more information on how to use that here:
https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key

Regarding debugging, [setting the secret `ACTIONS_STEP_DEBUG` to `true`](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging)  gives a lot of extra debug output in the log.

**Comment by aaronsky** [comment]
Oooh I'll have to try with that debug flag. Thanks! I've since implemented my own cross-build artifact caching system that does not use this action.
