### ISSUE TITLE
404 when key contains slash

### ISSUE THREAD

**Issue by alexlamsl** [actions/cache#53]
I think this has the same root cause as #43, except I am using my own custom string with slash (`tmp release/benchmark`) and receives 404 when trying to save the cache.

https://github.com/alexlamsl/UglifyJS2/runs/287169751
![404](https://user-images.githubusercontent.com/1898413/68158456-a3c9ec80-ff8a-11e9-83cf-3f631d8e455c.png)

**Comment by chancancode** [comment]
Seems like the cache key should be URL-encoded!

**Comment by joshmgross** [comment]
The cache key is already URL-encoded (see [`cacheHttpClient.ts`](https://github.com/actions/cache/blob/master/src/cacheHttpClient.ts#L72)) but I think there's some middleware on the server-side that's decoding it incorrectly, leading to the 404.

I'll leave this open since https://github.com/actions/cache/issues/43 has already been closed.

**Comment by fsimonis** [comment]
This issue extends to other symbols such as `+`.

I am compiling C++ code using the compilers `g++` and  `clang++`, which I put in the build matrix and in the cache key name.

**Comment by alexlamsl** [comment]
Yes, `%` also doesn't work etc.

Wouldn't be so problematic if we can manipulate strings to replace certain characters, but since we can't it is kind of a showstopper issue 😓

**Comment by joshmgross** [comment]
Just an update, we're rolling out a fix on the server-side for this sometime today or early next week.

**Comment by zarenner** [comment]
The fix for the `/` issue has been deployed:
![image](https://user-images.githubusercontent.com/13670625/68520100-ff75cd80-0249-11ea-971d-18be19fc38ff.png)

The fix for other special characters such as `+` and `%` is still in progress.

@alexlamsl while it's true that there isn't a replace expression [function](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#functions) that would help here, you should be able to use [`::set-output`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-output-parameter-set-output) with `sed` or similar to do string replacement as a workaround.
e.g.
```
    - name: Sanitize key
      id: sanitize-key
      run: echo "::set-output name=key::$(echo $key | sed 's/+/plus/g')"  
    - uses: actions/cache@v1
      with:
        key: ${{ steps.sanitize-key.outputs.key }}
        path: .
```
Not the most ideal workaround, but unless I'm misunderstanding hopefully that'll work for you in the meantime!

**Comment by alexlamsl** [comment]
@zarenner thanks for the fix & the tip on string manipulations :+1:
