### ISSUE TITLE
restore-keys documentation

### ISSUE THREAD

**Issue by skjolber** [actions/cache#532]
Please document the cache behaviour when there is multiple hits on **restore-keys**. It seems to me that it restores the most recently saved match. If so, does the cache have any logic to determine the in-scope cache entry for branches of main (given that the main might continue to see new commits before a branch is merged)? In other words, could a cache from a sibling commit be restored?

**Comment by dhadka** [comment]
:wave: Hi @skjolber, the [behavior of restore-keys is documented here](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key).  If anything is unclear or could be expanded, please let us know.

> It seems to me that it restores the most recently saved match

Yes, that is correct.

> If so, does the cache have any logic to determine the in-scope cache entry for branches of main (given that the main might continue to see new commits before a branch is merged)? In other words, could a cache from a sibling commit be restored?

Caches will always prefer matches on the current branch over `main` or other parent branches.  But there's nothing to prevent a cache from a sibling commit from being restored.  This is especially true given evictions can happen.  I could create a branch that restores cache X from `main` due to a prefix match, stop working for a week so this cache gets evicted, then push another change that will restore cache Y created at a different time, again due to a prefix match.

**Comment by skjolber** [comment]
Thanks!
