### ISSUE TITLE
The example Haskell cache setup is insufficient

### ISSUE THREAD

**Issue by nomeata** [actions/cache#555]
The recommendet setup for Haskell according to https://github.com/actions/cache/blob/main/examples.md#haskell---cabal is
```
- name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
  uses: actions/cache@v2
  with:
    path: |
      ~/.cabal/packages
      ~/.cabal/store
      dist-newstyle
    key: ${{ runner.os }}-${{ matrix.ghc }}
```
but this is not a good setup: The key doesn’t vary when the code or dependencies vary, so once the cache has been created, it will re-use the same cache over and over again, even as dependencies change. (This may be confusing to people migrating from Travis, which would always update the cache if the cache directories have changes).

A possible fix that may work well enough in many cases is to do write
```
- name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
  uses: actions/cache@v2
  with:
    path: |
      ~/.cabal/packages
      ~/.cabal/store
      dist-newstyle
    key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
    restore-keys: cabal-${{ runner.os }}-${{ matrix.ghc }}-
```

**Comment by vsvipul** [comment]
@nomeata Would you like to open a PR for this change?

**Comment by vsvipul** [comment]
@nomeata Would you like to open a PR for this change?

**Comment by langston-barrett** [comment]
Not sure whether to open a new issue or reopen this one, but in cabal-3.12 or later, the store is written to `~/.local/state/cabal/store` instead of `~/.cabal/store` (to respect the XDG Base Directory Specification).

For most use-cases, the best option would be to cache `${{ steps.setup-haskell.outputs.cabal-store }}` rather than `~/.cabal/store`, where `setup-haskell` is a step that runs [`haskell-actions/setup`](https://github.com/haskell-actions/setup). Not sure you'd want to specifically recommend using `haskell-actions/setup` in this project's docs, though.
