### ISSUE TITLE
Debugging output overwhelms when using this action via NPM API from our action

### ISSUE THREAD

**Issue by bahmutov** [actions/cache#560]
Our https://github.com/cypress-io/github-action is using actions/cache via NPM module, we are using v1.0.6

The problem is that if we want to debug our action by setting `ACTIONS_STEP_DEBUG: true` then the actions/cache prints _every single file_ that we cache during the install. And these could be millions of files, it completely swamps the logs. Is there a way to disable debug logging when using the `@actions/cache` module?

In our code we use it 

```js
const { restoreCache, saveCache } = require('@actions/cache')

const restoreCachedNpm = () => {
  core.debug('trying to restore cached NPM modules')
  const NPM_CACHE = getNpmCache()
  return restoreCache([NPM_CACHE.inputPath], NPM_CACHE.primaryKey, [
    NPM_CACHE.restoreKeys
  ]).catch((e) => {
    console.warn('Restoring NPM cache error: %s', e.message)
  })
}
```

**Comment by rcowsill** [comment]
> Our https://github.com/cypress-io/github-action is using actions/cache via NPM module, we are using v1.0.6

@bahmutov The source for the NPM package [@actions/cache](https://www.npmjs.com/package/@actions/cache) is in the [actions/toolkit](https://github.com/actions/toolkit) repo.

The collision between that package's name on NPM and this action's repo name is... unfortunate.

**Comment by rcowsill** [comment]
> Wait, how does it class between "github-action" and "actions/cache", isn't there "s" and namespace

Sorry, I should have been clearer about which package and repo I was talking about:

- This repo (https://github.com/actions/cache) is the source of the GitHub Action [actions/cache](https://github.com/marketplace/actions/cache).
- The NPM Package [@actions/cache](https://www.npmjs.com/package/@actions/cache) is part of https://github.com/actions/toolkit.

Your action https://github.com/cypress-io/github-action is using the NPM package `@actions/cache`, which isn't the same as the `actions/cache` in this repo.

I think this issue needs to be reported over at https://github.com/actions/toolkit rather than here.

**Comment by bahmutov** [comment]
:) I am so sorry for bothering @rcowsill my bad! Naming is hard, just like caching :)
