### ISSUE TITLE
[Feature Request] Expose ref for all deployment_status events

### ISSUE THREAD

**Issue by kylemh** [actions/cache#598]
I see that deployment_status events dont have a ref so we can't install to the cache from this job.

How would I make it so I install dependencies from the push that triggered the `deployment_status` and then leverage those cached dependencies for the action relying on the `deployment_status` event?

For reference, I'm essentially trying to do this workflow:

https://glebbahmutov.com/blog/develop-preview-test / https://www.philgiese.com/post/e2e-with-vercel

**Comment by kylemh** [comment]
Basically, how would I cache dependencies in this workflow:

https://github.com/kylemh/cypress-preview-url-issue

**Comment by mthines** [comment]
+1 I have the same need

**Comment by mthines** [comment]
https://github.com/cypress-io/github-action/issues/385

**Comment by rodilo** [comment]
Having the same issue.

**Comment by kylemh** [comment]
Why was this closed? You said yourself that it's a problem and will only be fixed if others want it fixed.

**Comment by aparna-ravindra** [comment]
@kylemh this is by design currently. Hence closed the issue.

**Comment by hensansi** [comment]
@aparna-ravindra I think that the issue isn't the closing of the thread but on how the situation was handled.

`We can revisit if there is more ask from the community.` -> `close` feels somewhat mute to the issue. I think that it is usually better to transform the issue into a discussion, given that is a design/feature decision that will need votes and `ask from the community.`

I checked and there is one already, https://github.com/actions/cache/discussions/516, which I "linked" to this issue. For the rest of the participants just go there and discuss/vote on the issue so we can get this prioritized.

**Comment by kylemh** [comment]
In my experience, closing an issue means the issue will NEVER be resolved, the issue IS resolved, or the issue is no longer relevant.

Even if this specific practical use is dismissed, conceptually I don't understand why `deployment_status` would not have a scope? It can change as commits are added to a branch. It should have access to the ref.

**Comment by aparna-ravindra** [comment]
Reopening the issue to continue the conversation. 

> I don't understand why deployment_status would not have a scope

`deployment_scope` can have a ref (scope) if the deployment was created on a branch or tag and the action will work if it does. It depends on how the deployment event was created. If the deployment event was created with commit SHA (and not a branch or tag), then there is no ref associated and the action will not support it. 

Since ref (scope) is a mandatory property of a cache object as per current design, we will not be able to support events not associated with a ref. Hence this issue should not be considered as a bug. However, we could treat it as a feature request to support events with no ref.

> I checked and there is one already, https://github.com/actions/cache/discussions/516

Thank you for following up on this discussion. Let's use the discussion to understand more and hear from the community. The issue is tagged in the discussion. We can use it to unify all discussions. 
From the perspective of this issue, it might not be possible to take up this design change at the current time. With this understanding, I suggest to close this issue and continue in the discussion thread as a feature request.

**Comment by kylemh** [comment]
> However, we could treat it as a feature request to support events with no ref.

Let's do that! Now, is this issue in the right repo?

**Comment by aparna-ravindra** [comment]
> Now, is this issue in the right repo?

Yes 👍

**Comment by kylemh** [comment]
Actually, my issue is that I think `deployment_status` should have a ref for every event. Vercel, Netlify, Render.io... many services will trigger deployment_status events from commits. If commit events for `deployment_status` had refs, there'd be no issue.

**Comment by aparna-ravindra** [comment]
Hey @kylemh ,
The action is only aware of the event that triggered the job. Hence, looking at the event for `deployment_status`, it is not possible to deduce the source branch/tag.
The `deployment_status` event can have a ref if the event was created with it. This is controlled by the system that is triggering the event. Hence this is not in the scope of this action and there is little that can be done without the information in the event.

**Comment by kylemh** [comment]
Right. Where do I post an issue requesting that this be changed. Even if it requires some sort of rearchitecting.

**Comment by aparna-ravindra** [comment]
There is a similar discussion in [this issue](https://github.com/actions/cache/issues/319). If you find it similar to your usecase, you are welcome to add your views.

**Comment by kylemh** [comment]
Ah. This looks basically like a dupe then.
