### ISSUE TITLE
Skip post actions/cache if cache exists

### ISSUE THREAD

**Issue by pascallosss** [actions/cache#66]
Is it possible to skip resaving the cached files if the cache already exists? I used the https://github.com/actions/cache/pull/37 example to save docker images for one of our Github Action. The execution time for the `run action` step improves from 1 minute to 8 seconds.. But resaving the cache takes 30-50 seconds which slows down the workflow speed more then it improves :-( 

Example github action exection time:
- GA without caching: +- 1:12m
```
  Set up job1s
  Run actions/checkout@v1 3s
  Docker login 5s
  Actions checkout 1s
  Run action 1m 2s
  Complete job
```

- GA with caching: +- 1:23m
Current steps and total time
``` Set up job 1s
  Run actions/checkout@v1 1s
  Docker login 2s
  Run actions/cache@v1 9s
  Load cached Docker layers 23s
  Actions checkout 1s
  Run action 8s
  Build image 0s # Skipped, because cache already exists
  Post actions/cache @v1 39s
  Complete job```

**Comment by dhadka** [comment]
Hi @pascallosss, the cache action should skip the post action if an exact match is found on the primary key.  If the cache matched on one of the prefixes, we will still save the cache using the primary key, since a prefix match indicates there are likely changes.  Do you see a message like `Cache hit occurred on the primary key ${primaryKey}, not saving cache.` in the post action?  Thanks!

**Comment by chrispat** [comment]
Saving and loading the docker tarball will likely be slower unless your layers are really expensive to generate.  In your example you have a very trivial docker container and you have added the overhead of exporting the layers to a tar uploading/downloading and importing those layers.

As with all incremental execution strategies you are not always going to see improvement.
