### ISSUE TITLE
Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by fb0** [actions/cache#671]
Hey there- thank you for this step, it's super useful!

I would like to report that I ran into an issue recently where the cache did not work as expected, instead I got the following error message:
```
[warning] Maximum call stack size exceeded
```
This happened when I tried to cache a folder with a large amount of small files (300000+ files) with fairly long filenames (80-100 chars).

In the previous executions of the same workflow I got the usual `Cache saved successfully` message , so I know that It worked before with the same config. It's just the number of files in that folder that I want to save and restore between executions that has been growing.

**Comment by vsvipul** [comment]
Hi @fb0  ! Is the repo on which you are using cache public? If yes, can you share link to the workflow run. If not, can you share the logs here?

**Comment by fb0** [comment]
Hey! It's a private repo unfortunately. There is not a lot of logging, here's what the UI shows for that build step that failed: 

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/88542062/146988976-bb787f67-7574-4102-9367-f02c6872c46c.png">

**Comment by fb0** [comment]
dcache build-steps-v3 is a simple cache step, trying to save a directory containing a lot of small files. Previously it was logging something like the step below- but it started failing when the number of files increased. My guess would be that there might be an issue when generating the file `manifest.txt` ? 

We fixed the issue by using SQLite instead of files on disk to store our data that we want to persist across builds.

**Comment by vsvipul** [comment]
Is this a Javascript repo? Doesn't seem to be an issue with our action but instead something to do with cache of your package manager which is throwing this error. For example, for npm, this can be fixed by clearing npm cache https://stackoverflow.com/questions/40566348/maximum-call-stack-size-exceeded-on-npm-install

If this has been fixed on your end, I'm going to go ahead and close this as not an issue on our end. We do have limits on total size  (around 10 GB) and upload chunks (around 90k). Number of chunks can be controlled by setting upload-chunk-size at https://github.com/actions/cache/blob/3bb5ffcc9c78302e6ddb66e954f54ec3806083e1/action.yml#L14 . There are no limits on the number of files that can be cached on our end. 

Feel free to reopen with more details if the issue comes up again. Thanks.

**Comment by malob** [comment]
This is still and issue for me.

**Comment by gtrepta** [comment]
> There are no limits on the number of files that can be cached on our end.

This is untrue. If the list of files is large enough, then a call stack limit is reached on line 6244 of [this source file](https://raw.githubusercontent.com/actions/cache/1bd1e32a3bdc45362d1e726936510720a7c30a57/dist/save-only/index.js):

```js
...
                    // Push the child items in reverse
                    const childLevel = item.level + 1;
                    const childItems = (yield __await(fs.promises.readdir(item.path))).map(x => new internal_search_state_1.SearchState(path.join(item.path, x), childLevel));
                    stack.push(...childItems.reverse());
                }
...
```

The exception can be reproduced by the same pattern in this example:

```js
stack = [];

for (i = 0; i < 200000; i++) {
    stack.push(i);
}

newstack = [];

newstack.push(...stack.reverse());
```
