### ISSUE TITLE
Post actions failed

### ISSUE THREAD

**Issue by alienxp03** [actions/cache#72]
I am writing the actions right now for a Rails app with below setup. However it's failing on the post action. Seems like `hashFiles` is looking for `Gemfile.lock` at the wrong place. 

```ruby
- uses: actions/cache@v1
      id: bundle-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
```

```ruby
Post actions/cache@v10s

##[error]The template is not valid. Could not find file '/home/runner/work/my-app/my-app/Gemfile.lock'.
```

**Comment by cristi** [comment]
I have the exact same problem with database-cleaner

**Comment by joshmgross** [comment]
Is the `Gemfile.lock` being removed during your build?

>Seems like `hashFiles` is looking for `Gemfile.lock` at the wrong place.

What is the correct place?

**Comment by alienxp03** [comment]
@cristi Thanks for the tips. Still happening though after I've upgraded the gem. Was 1.6.2.

@joshmgross Should be `/home/runner/work/my-app/my-app/Gemfile.lock`

**Comment by cristi** [comment]
@alienxp03 it's actually weird that it started working with version database-cleaner v1.7 because there still is a `Gemfile.lock` in the `examples` folder. But I did try a bunch of things and it started working after I upgraded. However, this is not even close to a solution :) There might be `Gemfile.lock`s in different places in a bundle so I think somewhat changing the `key` should fix it

**Comment by joshmgross** [comment]
@alienxp03 Are you hitting this issue still? We've rolled out some changes to the runner that should fix some `hashFiles` scenarios

**Comment by dhadka** [comment]
Closing this issue since there hasn't been any activity for 10 days.  Please re-open or create a new issue if this is still occurring.
