### ISSUE TITLE
Caching `/nix/store` is ok, but unable to restore it.

### ISSUE THREAD

**Issue by drupol** [actions/cache#749]
Hi,

I'm trying to improve the workflow in here: https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/.github/workflows/build.yaml

Basically I would like to cache the build dependencies once, and re-use them in each book editions (8), so there is no need to download 8 times the same thing.

Caching the `/nix/store` directory works: https://github.com/drupol/milewski-ctfp-pdf/runs/5348859880?check_suite_focus=true

![image](https://user-images.githubusercontent.com/252042/155872058-57545abd-5d17-4e20-861f-56caea4db8c2.png)

Restoring it fails: https://github.com/drupol/milewski-ctfp-pdf/runs/5348868521?check_suite_focus=true

![image](https://user-images.githubusercontent.com/252042/155872066-e26d365c-4219-4c1a-bb7f-c80ebbbbfc21.png)

Do you have any idea on how I could fix this ?

**Comment by Niols** [comment]
I'm facing a similar issue and only started looking for solutions, but there seem to be actions that manage to use the cache on `/nix/store`, eg. https://github.com/rikhuijzer/cache-install. I'm just putting this here for documentation purposes and I will come back if I find a solution.

**Comment by drupol** [comment]
> I'm facing a similar issue and only started looking for solutions, but there seem to be actions that manage to use the cache on `/nix/store`, eg. https://github.com/rikhuijzer/cache-install. I'm just putting this here for documentation purposes and I will come back if I find a solution.

I tried this action before, and it does not work at all. For some reason, it's not recognized anymore.

**Comment by rikhuijzer** [comment]
> I tried this action before, and it does not work at all. For some reason, it's not recognized anymore.

Feel free to send in bug reports or, even better, pull requests.

Restoring fails because `/nix/store` is set to read-only, so this GitHub cache action doesn't have the permissions to override/add stuff there. Note that my `cache-install` action is a wrapper around the GitHub cache action and aimed to solve some of these kind of issues.

More generally, if it's only about PDF artifacts, I can highly recommend [Tectonic](https://github.com/tectonic-typesetting/tectonic). Tectonic is a drop-in replacement for other LaTeX builders and downloads dependencies automatically. I've been using it inside a GitHub Action for months and it works flawlessly.

**Comment by tpwrules** [comment]
I figured out how to do this here: https://github.com/tpwrules/nixos-m1/blob/22f39d12f022deddf0a4f8e5139b8b88f12e95ed/.github/workflows/installer.yml

It's not exactly the cleanest solution, and it's relatively slow, but it does work properly. I might try and fix the fact that `nix-collect-garbage` deletes pinned versions of nixpkgs but it's kind of necessary to prevent the cache growing without bound if you keep re-uploading it like I do.

**Comment by drupol** [comment]
Do you think it would be a good idea to automatized these steps the Github Action (https://github.com/cachix/install-nix-action) from @domenkozar ?

**Comment by bishal-pdMSFT** [comment]
Reading through the thread, looks like there a solution built using https://github.com/cachix/install-nix-action. If there is no requirement on cache action, I will close this issue.

**Comment by R-VdP** [comment]
@bishal-pdMSFT I don't see how this is solved in install-nix-action ? There is an option to use Cachix, which is really useful, but not entirely the same use-case.
I'd still be interested in being able to easily cache the nix store between CI runs without needing to upload all store paths to Cachix.

**Comment by bishal-pdMSFT** [comment]
@R-VdP I was referring to `install-nix-action` based solution proposed by @tpwrules [here](https://github.com/actions/cache/issues/749#issuecomment-1066009534). 
Another option which I think does not involve Cachix uploads is to use https://github.com/rikhuijzer/cache-install as mentioned by @rikhuijzer [here](https://github.com/actions/cache/issues/749#issuecomment-1059944800).

The problems associated with niz store permissions are something which I don't think would fit in the scope of actions/cache action and hence my recommendation would be to use a solution built on top of it.

**Comment by tpwrules** [comment]
My solution is unnecessarily slow and complicated.

This issue could be resolved easily by running the untar in the restore with root privileges using sudo. Is this not an acceptable solution?

**Comment by domenkozar** [comment]
@R-VdP note that Cachix will soon gain support for zstd, massively speeding up the time needed to upload/download store paths.

**Comment by joneshf** [comment]
If anyone else is like I was just a bit ago and was still looking for a decent solution to this problem, using the `nix` command–instead of the `nix-*` commands–can be an option. With the `nix` command, you can pass it a `--store` flag to specify an alternate location for the nix store. If you make that location somewhere that the cache action can write–like `~/nix`–it should allow you to cache your nix store!

Depending on what you're doing, using the `nix` command might require you to change some stuff around. E.g. I had to switch over to using flakes in https://github.com/joneshf/terraform-provider-openwrt/pull/83 in order to run a similar command. For posterity, I went from running `nix-shell --run 'make test'` to running `nix --store ~/nix develop . --command make test`; and then caching the `~/nix` directory with this `actions/cache` action. But if you can switch over to the `nix` command, you might also be able to benefit from this approach.

**Comment by joneshf** [comment]
Oh, interesting! Lemme know if you find a better path to use.

**Comment by deemp** [comment]
Settings `store = /home/runner/nix` indeed works. However, the symlinks become incorrect. 
E.g. to copy a `hello` binary, I run

```sh
nix build nixpkgs#hello
cp /home/runner/nix$(realpath result)/bin/hello .
```

**Comment by deemp** [comment]
Nix store caching plus some extra features is implemented in https://github.com/nix-community/cache-nix-action/.
