### ISSUE TITLE
5

### ISSUE THREAD

**Issue by karalex** [actions/cache#796]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by xzpix** [comment]
I'm really not sure what u mean. I have an admin, stalker, hacker or whomever in my system and using my ip address it says unknown network but I can every now and again connect to mine. This has been a very very long time. They manipulate the screen so bad to fit them but I've told them I have yrs of video and guess they don't believe me  I've found where they've totally made fun of me and they clone and use apps. It's pathetic. So, anyway they tell lies and there's tons of THEIR made up edited logs and my original s so feel free to reach out

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Aleksi Karabanov ***@***.***>
Sent: Saturday, April 30, 2022, 2:59 PM
To: actions/cache ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [actions/cache] 5 (Issue #796)


Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue relates to code in this repository.

  *   If you have found a security issue please submit it here<https://hackerone.com/github>
  *   If you have questions about writing workflows or action files, then please visit the GitHub Community Forum's Actions Board<https://github.community/c/code-to-cloud/github-actions>
  *   If you are having an issue or question about GitHub Actions then please contact customer support<https://help.github.com/en/articles/about-github-actions#contacting-support>

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.
