### ISSUE TITLE
Add content in cache myself

### ISSUE THREAD

**Issue by Elikill58** [actions/cache#935]
I'm actually using [this script](https://github.com/Elikill58/Negativity/blob/v2/setup_spigot.sh) to setup project. After, I can do everything.

I see that I can't run this file only on first setup, so I'm trying to run it everytime, and cache all content created by it.

How can I add in cache all generated files ? Like use bash command to put them on cache ? Because I'm trying on another fork ([here](https://github.com/ArkemisMC/Negativity/tree/v2)) and when it fail, the cache isn't ran. I can't check if it's fine or not, and idk if files are well saved.

Actual in-dev workflow [here](https://github.com/ArkemisMC/Negativity/blob/v2/.github/workflows/build.yml)

**Comment by pdotl** [comment]
Hey @Elikill58, from the above workflow, the `cache` step tries to restore a cache but does not finds any cache with that key. The post cache step is which actually creates the cache in case the cache does not exist, but that step is skipped since the previous step of the workflow failed.

So, after fixing the failing step, a successful workflow run should create the cache for you. In order to have more visibility  over your caches, you could checkout the [Cache API](https://docs.github.com/en/rest/actions/cache#list-github-actions-caches-for-a-repository) or the [gh cli](https://github.com/actions/gh-actions-cache).

**Comment by pdotl** [comment]
Closing this for now. Feel free to re-open if you need further help.
