### ISSUE TITLE
EACCES error since actions/core 1.10.0 is used

### ISSUE THREAD

**Issue by priv-kweihmann** [actions/cache#957]
With latest 3.0.11 release I get the following when using the action in a custom container

```
##[group]Run actions/cache@v3
with:
  path: /opt/build/cache
  key: abcdefg
env:
  PYTHONIOENCODING: utf8
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
##[endgroup]
##[command]/usr/bin/docker exec  3b546736d77f8824d189889fc7b02137c045e2233570b125fb885a0a9f770eca sh -c "cat /etc/*release | grep ^ID"
##[error]EACCES: permission denied, open '/__w/_temp/_runner_file_commands/save_state_791c05c8-fe09-4487-a97d-52973eee2141'
```

- `/__w/` is set to 0777 so this isn't a permissions issue of the file system
- release 3.0.10 works without any issues here

**Comment by bishal-pdMSFT** [comment]
This looks related to file commands changes done recently. @pdotl @rentziass can you please take a priority look.

**Comment by pdotl** [comment]
Hi there @priv-kweihmann, we have noticed this issue is similar to [#956](https://github.com/actions/checkout/issues/956) posted at `actions/checkout`. The issue has to to do with [dockerfile usage of actions not supporting non-root users.](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user). Please see if the following workarounds would work for your case:

Quoting from [#956](https://github.com/actions/checkout/issues/956) 

> ### Workarounds (unsupported)
> - Use actions/checkout@v3.0.2 in your workflow (will be deprecated)
> - Match the UID of the host runner user (e.g. UID-1001 on ubuntu-latest today) to the UID of the user on the jobContainer
> - Override the default container user and use 'root':
>   ```yaml
>   container: 
>       image: alpine:latest
>       options: --user root
>   ```

**Comment by priv-kweihmann** [comment]
@pdotl thanks I will take a look if I can manage to modify my container accordingly

**Comment by priv-kweihmann** [comment]
Update: updating the container to use matching UIDs did it for me - thanks for the support
