### ISSUE TITLE
Cache service responded with 404

### ISSUE THREAD

**Issue by rashedmyt** [actions/cache#96]
I'm trying to cache the ccache directory, it fails with warning `Cache service responded with 404` and cache doesn't get saved.. The weird thing is it happens only on one job repeatedly. The size of the cache is around 25M which is way less than 400M.

https://github.com/rashedmyt/turtlecoin/runs/303082196

The remaining jobs are getting cached perfectly..

**Comment by dhadka** [comment]
Hi @rashedmyt.  It's likely failing because of the + in the cache key - `ccache-linux-g++-7`.  You should be able to fix this by either changing the [matrix label](https://github.com/rashedmyt/turtlecoin/blob/b48239928efcfc2ff5f3c6dbf525b616a49ac96d/.github/workflows/matrix.yml#L25) or sanitizing the key to remove the invalid characters.  See this comment for an example - https://github.com/actions/cache/issues/53#issuecomment-552052769

Please note that we are working on a fix for this issue, but until it is release you will need to use one of the workarounds above.

**Comment by rashedmyt** [comment]
Thanks for the quick reply, renaming the label worked..
